### ISSUE TITLE
Antonios nut house not bound to a room in the map

### ISSUE THREAD

**Issue by lsilbers** [the-mappinator-3000/groupon-maps-android#9]

**Comment by lsilbers** [comment]
@nutritious

**Comment by lsilbers** [comment]
Running with scissors
shapes and colors
and the patio are also missing

**Comment by nutritious** [comment]
will fix soon

**Comment by nutritious** [comment]
The fix is pending CR: https://github.com/the-mappinator-3000/groupon-maps-android/pull/12
